import React from 'react';
import Head from 'next/head';
import PropTypes from 'prop-types';
import Navbar from './Navbar';

function Layout({ title, children }) {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </div>
  );
}

Layout.defaultProps = {
  title: '',
};

Layout.propTypes = {
  title: PropTypes.string,
  children: PropTypes.node.isRequired,
};

export default Layout;
